server:
  port: 8081

#spring:
#  security:
#    user:
#      name: zhao
#      password: zhao123

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zhao19910716